{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "from math import *\n",
    "\n",
    "class MusicSimilarity:\n",
    "    \n",
    "    csv_file = 'Music.csv'\n",
    "    \n",
    "    dataset = []\n",
    "    artist_music = []\n",
    "    music_features = []\n",
    "    \n",
    "    dataset_attributes = [\n",
    "        'acousticness', \n",
    "        'artists', \n",
    "        'danceability', \n",
    "        'energy', \n",
    "        'id', \n",
    "        'liveness', \n",
    "        'loudness', \n",
    "        'name', \n",
    "        'popularity', \n",
    "        'speechiness', \n",
    "        'tempo', \n",
    "        'valence'\n",
    "    ]\n",
    "    \n",
    "    artist_music_attributes = [\n",
    "        'artists',\n",
    "        'name',\n",
    "        'id',\n",
    "    ]\n",
    "    \n",
    "    music_features_attributes = [\n",
    "        'id',\n",
    "        'acousticness',  \n",
    "        'danceability', \n",
    "        'energy', \n",
    "        'liveness', \n",
    "        'loudness', \n",
    "        'popularity', \n",
    "        'speechiness', \n",
    "        'tempo', \n",
    "        'valence'\n",
    "    ]\n",
    "    \n",
    "    def load_dataset(self):\n",
    "        \n",
    "        input_file = csv.DictReader(open(self.csv_file, encoding='utf8'))\n",
    "        \n",
    "        for row in input_file:\n",
    "\n",
    "            temp_dict = {}\n",
    "            for key in row:\n",
    "                \n",
    "                if key not in self.dataset_attributes:\n",
    "                    continue\n",
    "                temp_dict[key] = row[key]\n",
    "            \n",
    "            self.dataset.append(temp_dict)\n",
    "        \n",
    "        print('[Dataset Loaded Successfully] \\n********************************\\n Row 0 =>', self.dataset[0], '\\n')\n",
    "    \n",
    "    def get_artist_music(self):\n",
    "        \n",
    "        \n",
    "        for dict_row in self.dataset:\n",
    "            \n",
    "            temp_dict = {}\n",
    "            \n",
    "            for key in dict_row:\n",
    "        \n",
    "                if key in self.artist_music_attributes:            \n",
    "                    temp_dict[key] = dict_row[key]\n",
    "            \n",
    "            self.artist_music.append(temp_dict)\n",
    "    \n",
    "        print('[Generating Artist Music] \\n********************************\\n Row 0 =>', self.artist_music[0], '\\n')\n",
    "    \n",
    "    def get_music_features(self):\n",
    "        \n",
    "        for dict_row in self.dataset:\n",
    "            \n",
    "            temp_dict = {}\n",
    "            \n",
    "            for key in dict_row:\n",
    "        \n",
    "                if key in self.music_features_attributes:            \n",
    "                    temp_dict[key] = dict_row[key]\n",
    "            \n",
    "            self.music_features.append(temp_dict)\n",
    "    \n",
    "        print('[Generating Music Features] \\n********************************\\n Row 0 =>', self.music_features[0], '\\n')\n",
    "        \n",
    "    \n",
    "    def euclidean_distance(self, x, y): \n",
    "        return sqrt(sum(pow(a - b, 2) for a, b in zip(x, y))) \n",
    "    \n",
    "    def manhattan_distance(self, x, y): \n",
    "        return sum(abs(a - b) for a, b in zip(x, y))\n",
    "    \n",
    "    def square_rooted(self, x):\n",
    " \n",
    "        return round(sqrt(sum([a * a for a in x])), 3)\n",
    " \n",
    "    def cosine_similarity(self, x, y):\n",
    "\n",
    "        numerator = sum(a * b for a, b in zip(x, y))\n",
    "        denominator = self.square_rooted(x) * self.square_rooted(y)\n",
    "        return round(numerator / float(denominator), 3)\n",
    "\n",
    "    def jaccard_similarity(self, x, y):\n",
    " \n",
    "        intersection_cardinality = len(set.intersection(*[set(x), set(y)]))\n",
    "        union_cardinality = len(set.union(*[set(x), set(y)]))\n",
    "        return intersection_cardinality/float(union_cardinality)\n",
    "\n",
    "    def get_music_values(self, music_id):\n",
    "        \n",
    "        for row in self.music_features:\n",
    "            \n",
    "            if row['id'] == music_id:\n",
    "                \n",
    "                temp = []\n",
    "                for key in row:\n",
    "                    \n",
    "                    if key != 'id':\n",
    "                         temp.append(float(row[key]))\n",
    "                            \n",
    "                return temp\n",
    "            \n",
    "    def generate_music_similarity(self, music_id_1, music_id_2):\n",
    "        \n",
    "        x = self.get_music_values(music_id_1)\n",
    "        y = self.get_music_values(music_id_2)\n",
    "        \n",
    "        print('\\nValues: ',x, y)\n",
    "        \n",
    "        print('[Euclidean Distance] :', self.euclidean_distance(x, y))\n",
    "        print('[Manhattan Distance] :', self.manhattan_distance(x, y))\n",
    "        print('[Cosine Similarity] :', self.cosine_similarity(x, y))\n",
    "        print('[Jaccard Similarity] :', self.jaccard_similarity(x, y))\n",
    "    \n",
    "    def mean(self, data):\n",
    "        return [float(sum(col))/len(col) for col in zip(*data)]\n",
    "    \n",
    "    \n",
    "    \n",
    "    def get_artists_values(self, artists_name):\n",
    "        \n",
    "        music_ids = []\n",
    "        \n",
    "        for row in self.artist_music:    \n",
    "            if row['artists'] == artists_name:\n",
    "                music_ids.append(row['id'])\n",
    "        \n",
    "        values_list = []\n",
    "        \n",
    "        for music_id in music_ids:\n",
    "            values_list.append(self.get_music_values(music_id))\n",
    "        \n",
    "        return self.mean(values_list)\n",
    "        \n",
    "        \n",
    "    def generate_artists_similarity(self, artists_name_1, artists_name_2):\n",
    "        \n",
    "        x = self.get_artists_values(artists_name_1)\n",
    "        y = self.get_artists_values(artists_name_2)\n",
    "        \n",
    "        print('\\nValues: ',x, y)\n",
    "        \n",
    "        print('[Euclidean Distance] :', self.euclidean_distance(x, y))\n",
    "        print('[Manhattan Distance] :', self.manhattan_distance(x, y))\n",
    "        print('[Cosine Similarity] :', self.cosine_similarity(x, y))\n",
    "        print('[Jaccard Similarity] :', self.jaccard_similarity(x, y))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    \n",
    "    #task a (Loading the dataset)\n",
    "    \n",
    "    ms = MusicSimilarity()\n",
    "    ms.load_dataset()\n",
    "    ms.get_artist_music()\n",
    "    ms.get_music_features()\n",
    "    \n",
    "    #task b (Finding Similarities)\n",
    "    \n",
    "    #music similarity\n",
    "    print('Music Similarity\\n*****************************\\n')\n",
    "    music_id_1 = '6KbQ3uYMLKb5jDxLF7wYDD'\n",
    "    music_id_2 = '6L63VW0PibdM1HDSBoqnoM'\n",
    "    \n",
    "    ms.generate_music_similarity(music_id_1, music_id_2)\n",
    "    \n",
    "    #artist simialrity\n",
    "    print('Artist Similarity\\n*****************************\\n')\n",
    "    artists_name_1 = \"['Carl Woitschach']\"\n",
    "    artists_name_2 = \"['Robert Schumann', 'Vladimir Horowitz']\"\n",
    "    \n",
    "    ms.generate_artists_similarity(artists_name_1, artists_name_2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Dataset Loaded Successfully] \n",
      "********************************\n",
      " Row 0 => {'acousticness': '0.995', 'artists': \"['Carl Woitschach']\", 'danceability': '0.708', 'energy': '0.195', 'id': '6KbQ3uYMLKb5jDxLF7wYDD', 'liveness': '0.151', 'loudness': '-12.428', 'name': 'Singende Bataillone 1. Teil', 'popularity': '0', 'speechiness': '0.0506', 'tempo': '118.469', 'valence': '0.779'} \n",
      "\n",
      "[Generating Artist Music] \n",
      "********************************\n",
      " Row 0 => {'artists': \"['Carl Woitschach']\", 'id': '6KbQ3uYMLKb5jDxLF7wYDD', 'name': 'Singende Bataillone 1. Teil'} \n",
      "\n",
      "[Generating Music Features] \n",
      "********************************\n",
      " Row 0 => {'acousticness': '0.995', 'danceability': '0.708', 'energy': '0.195', 'id': '6KbQ3uYMLKb5jDxLF7wYDD', 'liveness': '0.151', 'loudness': '-12.428', 'popularity': '0', 'speechiness': '0.0506', 'tempo': '118.469', 'valence': '0.779'} \n",
      "\n",
      "Music Similarity\n",
      "*****************************\n",
      "\n",
      "\n",
      "Values:  [0.995, 0.708, 0.195, 0.151, -12.428, 0.0, 0.0506, 118.469, 0.779] [0.604, 0.749, 0.22, 0.119, -19.924, 0.0, 0.929, 107.177, 0.88]\n",
      "[Euclidean Distance] : 13.588130061196782\n",
      "[Manhattan Distance] : 20.256399999999985\n",
      "[Cosine Similarity] : 0.997\n",
      "[Jaccard Similarity] : 0.058823529411764705\n",
      "Artist Similarity\n",
      "*****************************\n",
      "\n",
      "\n",
      "Values:  [0.9907999999999999, 0.6401999999999999, 0.29500000000000004, 0.1564, -11.616999999999999, 0.0, 0.04676, 119.87740000000001, 0.8012] [0.9934347826086958, 0.3643478260869565, 0.06795521739130436, 0.11367391304347826, -27.796695652173906, 8.652173913043478, 0.05031304347826086, 93.30465217391303, 0.2906391304347826]\n",
      "[Euclidean Distance] : 32.29773603658209\n",
      "[Manhattan Distance] : 52.466989130434804\n",
      "[Cosine Similarity] : 0.978\n",
      "[Jaccard Similarity] : 0.0\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
